name: npm-deploy
run-name: ${{ github.actor }}-${{ github.sha }}-npm-deploy
on:
  push:
    branches:
      - main
jobs:
  npm-run-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - run: npm run deploy -- --message "Deploy commit ${{ github.sha }}"

